// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as AppCss from "./App.css";
import LogoSvg from "./logo.svg";
import RescriptLogoSvg from "./rescript-logo.svg";

var logo = LogoSvg;

var rescriptLogo = RescriptLogoSvg;

function App(Props) {
  return React.createElement("div", {
              className: "App"
            }, React.createElement("header", {
                  className: "App-header"
                }, React.createElement("div", {
                      className: "logos"
                    }, React.createElement("img", {
                          className: "Rescript-logo",
                          alt: "rescript logo",
                          src: rescriptLogo
                        }), React.createElement("span", {
                          className: "Emoji"
                        }, "🧑‍💻"), React.createElement("img", {
                          className: "App-logo",
                          alt: "logo",
                          src: logo
                        })), React.createElement("p", undefined, "Edit", React.createElement("code", undefined, " src/App.res "), "and save to reload."), React.createElement("a", {
                      className: "App-link",
                      href: "https://reactjs.org",
                      rel: "noopener noreferrer",
                      target: "_blank"
                    }, "Learn ReScript/React")));
}

var _css;

var make = App;

export {
  logo ,
  rescriptLogo ,
  _css ,
  make ,
}
/* logo Not a pure module */
