// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.mjs";
import * as React from "react";
import * as ReactDom from "react-dom";
import * as IndexCss from "./index.css";

var root = document.querySelector("#root");

if (!(root == null)) {
  ReactDom.render(React.createElement(React.StrictMode, {
            children: React.createElement(App.make, {})
          }), root);
}

var _css;

export {
  _css ,
}
/*  Not a pure module */
